name: Keep Alive
on:
  schedule:
    - cron: "*/5 * * * *" #5min
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping frontend
        run: curl -s https://frontdoor-sigma.vercel.app/
